services:
  - type: web
    name: solicite-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install --legacy-peer-deps && node build.mjs
    startCommand: node --enable-source-maps dist/index.mjs
    healthCheckPath: /api/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: MERCADO_PAGO_ACCESS_TOKEN
        sync: false
